[project]
name = "emr-cli"
version = "0.0.1"
dependencies = [
    "click==7.1.2",
    "boto3~=1.26.6"
]

[project.optional-dependencies]
tests = [
  "pytest==7.2.2",
  "pyfakefs==5.12.0"
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
emr = "emr_cli.emr_cli:cli"