name: Spark Job Unit Tests
on: [push]
jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - 
      name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    -
      name: cache poetry install
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: ${{ runner.os }}-poetry-1.3.2-0
    - 
      name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - 
      name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - 
      name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: |
        source $VENV
        poetry install --no-interaction --no-root
    - 
      name: Install project
      shell: bash
      run: |
        source $VENV
        poetry install --no-interaction
    - 
      name: Run tests
      shell: bash
      run: |
        source $VENV
        pytest --cov emr_cli tests/